### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by jc-r** [dataminr/react-components#23]
Please I want to run the example inside folder. I did `grunt` and `bower install` but anything works. 
The index.html file inside /src/js/examples folder requires /dist and src/. How do I generate this folders?
Thanks

**Comment by jasonjohnson115** [comment]
You would also need to npm install in addition to the bower install before running grunt. Let me know if that helps or not.

**Comment by jc-r** [comment]
Yes, It works
I was doing `grunt` in Windows prompt and 'rm' command is not recognized.
Thank you.
