### ISSUE TITLE
Demo Website

### ISSUE THREAD

**Issue by DrEVILish** [dataminr/react-components#40]
Require a demo website to show off what your objects and work can do in a practical manor.

**Comment by jasonjohnson115** [comment]
Ryan, thank you for showing interest in what our components have to offer.
We at one point in time did host a demo site, but found it easier to offer
an example application to develop within after cloning the repository.
Instructions should be within the readme. Please let me know if this helps!

**Comment by jasonjohnson115** [comment]
Marking this issue as closed. We may revisit using ghpages again in the future if there's enough demand for it.
